const Colors1 = {
  white: '#fff',
  black: '#000',
  blue: '#5D5FEE',
  grey: '#BABBC3',
  light: '#F3F4FB',
  darkBlue: '#7978B5',
  red: 'red',
  themeColor: '#1E89A0',
  darkGrey: 'rgb(67,67,67)',
  lightBlack: 'rgb(32,32,32)',
};

const ImageString = {
  Main_BackGround_Image: require('../../assets/images/background1.jpg'),
  Club_DashBoard_BackImage: require('../../assets/images/dashboard_image.png'),
  Club_DashBoard_Biding: require('../../assets/images/biding_OverView.png'),
  Banner_Image: require('../../assets/images/regpic.jpg'),
  Avatar_ImageReg: require('../../assets/images/regpix1.png'),
  Avatar_ImageLog: require('../../assets/images/regpix2.png'),
  FaceBook_Logo: require('../../assets/images/facebookSocial.png'),
  Google_Logo: require('../../assets/images/googleSocial.png'),
  Home_Tab: require('../../assets/images/homeTab.png'),
  Search_Tab: require('../../assets/images/searchTab.png'),
  Add_Tab: require('../../assets/images/addTab.png'),
  Detail_tab: require('../../assets/images/detailTab.png'),
  Profile_Tab: require('../../assets/images/personIcon.png'),
  EditIcon: require('../../assets/images/EditIcon.png'),
  WorldPic: require('../../assets/images/world.png'),
  Edit_Icon: require('../../assets/images/edit_icon.png'),
  Three_Dots: require('../../assets/images/three_dots.png'),
  Card_Front: require('../../assets/images/card-front.png'),
};

const IconString = {
  Edit_Icon_Profile: require('../../assets/images/EditIconProfile.png'),
  SearchIcon: require('../../assets/images/SearchIcon.png'),
  Like_Icon: require('../../assets/images/likeIcon.png'),
  LikeIcon: require('../../assets/images/like_Icon.png'),
  CommentIcon: require('../../assets/images/comment_Icon.png'),
  Share_Icon: require('../../assets/images/share_Icon.png'),
  Filter_Icon: require('../../assets/images/filter_Icon.png'),
  Back_Icon: 'chevron-back-outline',
  Menu_Icon: 'reorder-two-outline',
  Chat_Bubbles: 'chatbubbles-sharp',
  Notification_Bell: 'notifications-outline',
  Bell: require('../../assets/images/bell.png'),
  Chat: require('../../assets/images/chat.png'),
  Dropdown: require('../../assets/images/dropdown.png'),
  Gallery: require('../../assets/images/gallery.png'),
  Dropdown: require('../../assets/images/dropdown.png'),
  Go_Back: require('../../assets/images/go_back.png'),
  Location: require('../../assets/images/location.png'),
  Music: require('../../assets/images/music.png'),
  Location: require('../../assets/images/location.png'),
  Pending: require('../../assets/images/pending.png'),
  Received: require('../../assets/images/received.png'),
  Search: require('../../assets/images/search.png'),
  Side_Nav: require('../../assets/images/side_nav.png'),
  Three_Dots_Vertical: require('../../assets/images/three_dots_vertical.png'),
  Upload_Media: require('../../assets/images/upload_media.png'),
  Video: require('../../assets/images/video.png'),
  Chat_Send: require('../../assets/images/chat_send.png'),

};

const NavigationString = {
  Register_Login: 'RegisterLogin',
  Register_Screen: 'RegisterScreen',
  Login_Screen: 'LoginScreen',
  Recover_Pass: 'RecoverPass',
  Enter_Otp: 'Enterotp',
  Create_pass: 'CreatePassword1',
  User_DashBoard: 'UserDashBoard',
  User_Detail: 'UserDetail',
  User_Profile: 'UserProfile',
  Add_Tab: 'AddTab',
  Search_Tab: 'SearchTab',
  Bottom_Controller: 'BottonTabController',
  Image_Tab: 'Image',
  Music_Tab: 'Music',
  Video_Tab: 'Video',
  Club_List: 'ClubChatList',
  User_Chat: 'ClubUserChat',
  RequestDj: 'Request',
  RequestPromotorList: 'PromotorRequestList',
  RequestList: 'requestList',
  Booking: 'booking',
  BookingList: 'bookingList',
  BookingPromotor: 'bookingPromotList',
  Pricing: 'PricingMenu',
  EcommercePricing: 'Ecommerce',
  SectionPricing: 'secPrice',
  UploadMedia: 'uploadMedia',
  Post_Job: 'PostJOB',
  Review_Screen: 'ReviewScreen',
  EditProfile: 'EditProfile',
  NotificationScreen: 'NotificaionScreen',
  Wallet: 'wallet',
  WalletDeposit:'WalletDeposit',
  WalletWithdraw:'WalletWithdraw'
};

export {Colors1, ImageString, NavigationString, IconString};
